# Generated by Django 4.1 on 2022-11-02 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: FruitLand', max_length=40, verbose_name='Nombre')),
                ('phone_number', models.CharField(help_text='Ej: 3455668', max_length=40, verbose_name='Télefono')),
                ('web_page', models.CharField(help_text='Ej: www.fruit.com', max_length=40, verbose_name='Página web')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
    ]
