# Generated by Django 4.1 on 2023-02-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0005_cartproducts_total'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
    ]
