# Generated by Django 4.1 on 2022-10-31 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShippingAddresses', '0002_rename_line1_shippingaddress_address_and_more'),
        ('Orders', '0003_alter_order_shipping_total_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShippingAddresses.shippingaddress'),
        ),
    ]
