# Generated by Django 4.1 on 2022-11-06 20:23

import MyApps.Orders.common
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShippingAddresses', '0003_alter_shippingaddress_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0005_order_accepted_alter_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedidos', 'verbose_name_plural': 'pedidos'},
        ),
        migrations.AlterField(
            model_name='order',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Tomar orden'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado el'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShippingAddresses.shippingaddress', verbose_name='Dirección de envio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.PositiveIntegerField(default=2000, verbose_name='Envio'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(MyApps.Orders.common.OrderStatus['CREATED'], 'EN PROCESO'), (MyApps.Orders.common.OrderStatus['ACCEPTED'], 'EN CAMINO'), (MyApps.Orders.common.OrderStatus['PAYED'], 'PAGADO'), (MyApps.Orders.common.OrderStatus['COMPLETED'], 'FINALIZADO'), (MyApps.Orders.common.OrderStatus['CANCELED'], 'CANCELADO')], default=MyApps.Orders.common.OrderStatus['CREATED'], max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
