# Generated by Django 4.1 on 2022-11-12 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillingProfiles', '0002_rename_cart_id_billingprofile_card_id'),
        ('Orders', '0007_order_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillingProfiles.billingprofile'),
        ),
    ]
