# Generated by Django 4.1 on 2023-02-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_order_billing_profile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
    ]
