# Generated by Django 4.1 on 2023-02-07 21:49

import MyApps.Orders.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(MyApps.Orders.common.OrderStatus['CREATED'], 'EN PROCESO'), (MyApps.Orders.common.OrderStatus['ACCEPTED'], 'EN CAMINO'), (MyApps.Orders.common.OrderStatus['PAYED'], 'PAGADO'), (MyApps.Orders.common.OrderStatus['COMPLETED'], 'FINALIZADO'), (MyApps.Orders.common.OrderStatus['CANCELED'], 'CANCELADO')], default=MyApps.Orders.common.OrderStatus['CREATED'], max_length=50, verbose_name='Estado'),
        ),
    ]
