# Generated by Django 4.1 on 2023-02-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0002_alter_purchasedetail_quantity_alter_purchase_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='purchase_id',
            new_name='purchase',
        ),
        migrations.AddField(
            model_name='purchasedetail',
            name='unit_price',
            field=models.IntegerField(default=1, verbose_name='Precio unitario'),
            preserve_default=False,
        ),
    ]
