# Generated by Django 4.1 on 2023-02-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0003_rename_purchase_id_purchasedetail_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_id',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='Id'),
            preserve_default=False,
        ),
    ]
