# Generated by Django 4.1 on 2023-02-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0004_purchase_purchase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total pago'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
    ]
