# Generated by Django 4.1 on 2023-02-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0005_purchase_total_alter_purchase_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.PositiveIntegerField(verbose_name='Total pago'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='unit_price',
            field=models.PositiveIntegerField(verbose_name='Precio unitario'),
        ),
    ]
