# Generated by Django 4.1 on 2023-03-13 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_alter_product_descripction'),
        ('Purchases', '0008_alter_purchasedetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.product', verbose_name='Producto'),
            preserve_default=False,
        ),
    ]
