# Generated by Django 4.1 on 2023-03-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0009_alter_purchasedetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='cantidad'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='unit_price',
            field=models.IntegerField(default=0, verbose_name='Precio unitario'),
        ),
    ]
