# Generated by Django 4.1 on 2022-11-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingProfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='cart_id',
            new_name='card_id',
        ),
    ]
