# Generated by Django 4.1 on 2023-02-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillingProfiles', '0002_rename_cart_id_billingprofile_card_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='billingprofile',
            table='billing_profiles',
        ),
    ]
