# Generated by Django 4.1 on 2022-10-25 16:28

import MyApps.Orders.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Carts', '0002_cart_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(MyApps.Orders.models.OrderStatus['CREATED'], 'EN PROCESO'), (MyApps.Orders.models.OrderStatus['PAYED'], 'PAGADO'), (MyApps.Orders.models.OrderStatus['COMPLETED'], 'FINALIZADO'), (MyApps.Orders.models.OrderStatus['CANCELED'], 'CANCELADO')], default=MyApps.Orders.models.OrderStatus['CREATED'], max_length=50)),
                ('shipping_total', models.IntegerField(default=2000)),
                ('total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Carts.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
