# Generated by Django 4.1 on 2023-02-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BillingProfiles', '0003_alter_billingprofile_table'),
        ('PromoCodes', '0005_alter_promocode_discount'),
        ('Orders', '0002_alter_order_options_order_billing_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BillingProfiles.billingprofile', verbose_name='Info de pago'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancelled_by',
            field=models.IntegerField(default=0, verbose_name='Cancelado por'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PromoCodes.promocode', verbose_name='Código de promoción'),
        ),
    ]
