# Generated by Django 4.1 on 2023-03-16 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ShippingAddresses', '0004_alter_shippingaddress_table'),
        ('Orders', '0003_alter_order_billing_profile_alter_order_cancelled_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ShippingAddresses.shippingaddress', verbose_name='Dirección de envio'),
        ),
    ]
