# Generated by Django 4.1 on 2023-02-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplier',
            table='provider',
        ),
    ]
