# Generated by Django 4.1 on 2023-02-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases', '0006_alter_purchase_total_alter_purchasedetail_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total pago'),
        ),
    ]
