# Generated by Django 4.1 on 2022-10-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='Ej: 12500', verbose_name='Precio'),
        ),
    ]
