# Generated by Django 4.1 on 2023-03-12 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_user_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='customer_id',
        ),
    ]
