# Generated by Django 4.1 on 2023-02-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saledetail',
            options={'verbose_name': 'Detalle de venta', 'verbose_name_plural': 'Detalle de ventas'},
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_man',
            field=models.IntegerField(default=0, verbose_name='Venta hecha por'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Ingreso'),
        ),
    ]
