# Generated by Django 4.1 on 2023-02-08 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_product_stock'),
        ('Sales', '0002_alter_saledetail_options_sale_sale_man_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Products.product'),
            preserve_default=False,
        ),
    ]
