# Generated by Django 4.1 on 2023-02-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_alter_saledetail_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='user',
            new_name='client',
        ),
    ]
