# Generated by Django 4.1 on 2022-11-07 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PromoCodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Código de promoción', 'verbose_name_plural': 'Códigos de promoción'},
        ),
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Generado el'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='used',
            field=models.BooleanField(default=False, verbose_name='¿Ya fue usado?'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Válido desde'),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Válido hasta'),
        ),
    ]
