# Generated by Django 4.1 on 2023-02-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromoCodes', '0004_alter_promocode_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Descuento'),
        ),
    ]
