# Generated by Django 4.1 on 2023-02-04 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_user_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
