# Generated by Django 4.1 on 2022-10-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_slug'),
        ('Carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='Carts.CartProducts', to='Products.product'),
        ),
    ]
