# Generated by Django 4.1 on 2022-11-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0003_alter_cart_subtotal_alter_cart_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Carrito', 'verbose_name_plural': 'Carritos'},
        ),
    ]
