# Generated by Django 4.1 on 2022-11-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Carts', '0004_alter_cart_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproducts',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
