# Generated by Django 4.1 on 2023-02-07 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Products', '0005_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_id', models.CharField(max_length=100, unique=True, verbose_name='Id')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Total pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'sales',
            },
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='cantidad')),
                ('total', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.sale')),
            ],
            options={
                'verbose_name': 'Detalle de la venta',
                'verbose_name_plural': 'Detalle de las ventas',
                'db_table': 'sale_detail',
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(through='Sales.SaleDetail', to='Products.product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
