# Generated by Django 4.1 on 2023-02-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_rename_user_sale_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='cantidad'),
        ),
    ]
