# Generated by Django 4.1 on 2022-10-30 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShippingAddresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='line1',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='city',
            new_name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='line2',
        ),
    ]
