# Generated by Django 4.1 on 2023-02-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShippingAddresses', '0003_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='shippingaddress',
            table='shipping_addresses',
        ),
    ]
