# Generated by Django 4.1 on 2022-10-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(help_text='Ej: 1', primary_key=True, serialize=False, verbose_name='Código')),
                ('name', models.CharField(help_text='Ej: Papaya', max_length=40, verbose_name='Nombre')),
                ('descripction', models.TextField(help_text='Ej: Und.x 100g', max_length=40, verbose_name='Descripcion')),
                ('price', models.IntegerField(help_text='Ej: 12500', verbose_name='Precio')),
                ('image_product', models.ImageField(upload_to='media', verbose_name='Imagen')),
                ('stock', models.IntegerField(help_text='Ej: 50', verbose_name='Cantidad')),
                ('status', models.IntegerField(choices=[[0, 'Disponible'], [1, 'Agotado']], default='Disponible', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'productos',
            },
        ),
    ]
